version: '3.5'
services:
  #  web:
  #    build: .
  #    ports:
  #      - "${port}:${port}"
  #    container_name: chat_backend
  #    stdin_open: true
  #    tty: true
  #    depends_on:
  #      - postgres
  #    environment:
  #      - port=${port}
  #      - httpsPort=${httpsPort}
  #      POSTGRES_HOST: postgres
  #      POSTGRES_USER: postgres
  #      POSTGRES_PASSWORD: changeme
  #  networks:
  #    - postgres

  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "${PGDATA}"
    volumes:
      - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
#    networks:
#      - postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped
#    networks:
#      - postgres

#networks:
#  postgres:
#    driver: bridge

volumes:
  postgres:
  pgadmin:

